### DISCUSSION TITLE
Inherit configuration from .github repo

### DISCUSSION THREAD

**Discussion by mmlb** [Mergifyio/mergify#2205] [Ideas]
I've asked this question in the websites chat a year or so ago but I can't find the conversation any more :/, so here goes again.

It would be great if mergify would look into an orgs/person's `.github` repo for common configuration that can then be extended or overwritten by per-repo config files. Github itself supports this paradigm with issue/pr templates, code of conducts etc. https://probot.github.io/ apps have this built in. It would be nice to have more tools doing the same and I'd really love for mergify to be one of them.

**Comment by jd** [comment]
Thanks @mmlb !
That's indeed a good idea. I've added it to our product backlog to gather requests. Feel free to upvote this conversation if anyone else think it's a good idea. That helps prioritize work.

**Reply by mkurz** [reply]
For GitHub orgs this is highly needed to organize configs in a central place, that's why I opened this PR: #4050
Please also have a look at the example I gave with release drafter in that PR how to nicely organize and extend configs. Thanks!

**Comment by ihostage** [comment]
@jd Hi, Julien! 👋 
In the latest [blog post](https://blog.mergify.com/mergify-changelog-2022q1/) is said 
> They allow filtering pull requests based on the name of the repository. This is useful to manage **a single Mergify configuration file across multiple repositories**.

Can you suggest, how we can use a single Mergify configuration across multiple repositories?

**Reply by jd** [reply]
You can write a configuration that works across multiple repositories by using something like
```yaml
pull_request_rules:
  - name: automerge
    conditions:
      - or:
          - and:
             - repository-name=myrepo
             - "#approved-reviews-by>=1"
          - and:
             - repository-name=myotherrepo
             - "#approved-reviews-by>=2"
    actions:
        merge:
```

You'll have to synchronize (`cp`) the file across the repositories yourself for the time being. :)
