### DISCUSSION TITLE
Is it possible to simplify backport for branches with a match operator and a capturing group?

### DISCUSSION THREAD

**Discussion by v1v** [Mergifyio/mergify#2865] [Q&A]
Hi there,

Given 

```yaml
  - name: backport patches to 7.x branch
    conditions:
      - merged
      - base=master
      - label=backport-7.x
    actions:
      backport:
        branches:
          - "7.x"
  - name: backport patches to 7.14 branch
    conditions:
      - merged
      - base=master
      - label=backport-7.14
    actions:
      backport:
        branches:
          - "7.14"
```

Is it possible to use one backport rule that uses the capturing group for the label when using the match operator `(~=)`? Therefore, I don't need to update the backport rules when a new maintenance branch is created?

Something like:

```yaml
  - name: backport patches
    conditions:
      - merged
      - base=master
      - label~=backport-(7.x)  ### <--- this is the trick to capture the group
    actions:
      backport:
        branches:
          - label.group(0)           ### <--- this is the trick to use the group in the label
```

Or do you see any major issues if the above is used somehow?
