### DISCUSSION TITLE
Assign assginee when PR was opened or converted from draft

### DISCUSSION THREAD

**Discussion by bochen87** [Mergifyio/mergify#2950] [Q&A]
Hi,

Is it possible to assign specific assignees once the PR has been opened or changed from draft? Would it re-assign again when I remove the assignee afterwards or would that not happen (I would not want that to happen, so only assign once and then forget about that PR essentially).

**Comment by jd** [comment]
Mergify rules are state-based, and the state is defined via conditions.
If your PR matches a condition, the actions are triggered. If the PR does not match the conditions, and then the conditions are matched again, the actions are triggered again.

To answer your specific question, you can assign a PR as soon as it's opened and not draft. You'd write something like:

```yaml
- name: assign non-draft PR
  conditions:
    - -draft
  actions:
    assign:
        add_users:
          - foobar
```

You might want to add slightly more conditions, but that's the idea.
If you remove the assignee afterward, it won't be re-added since the condition match won't change.

If you wanted to make sure the assignee is forced (which you don't want if IIUC), you'd need:

```yaml
- name: force assign non-draft PR to foobar
  conditions:
    - -draft
    - assignee!=foobar
  actions:
    assign:
        add_users:
          - foobar
```

If `foobar` is ever removed from the assignee list, the conditions result will change so it'll re-trigger the action, making sure `foobar` is never removed.

**Reply by bochen87** [reply]
Hi, thanks for your help!

I am trying something like this, but it give some errors

```
  - name: automatic assign when PR opened
    conditions:
      - -draft
    actions:
      assign:
          add_users:
            {% for reviewer in review_requested %}
               - "{{reviewer}}"
            {% endfor %}
```

`Invalid YAML @ line 25, column 14 ``` while scanning for the next token found character '%' that cannot start any token in "<unicode string>", line 25, column 14: {% for reviewer in review_request ... ^ `

**Reply by jd** [reply]
Right, you can't do that, unfortunately. The template part is inside the `add_users` value, not outside, which means you can't use Jinja to build the YAML itself.

I would try something like this:

```yaml
 - name: automatic assign when PR opened
    conditions:
      - -draft
    actions:
      assign:
          add_users:
               - "{{review_requested[0]}}"
               - "{{review_requested[1]}}"
               - "{{review_requested[2]}}"
               - "{{review_requested[3]}}"
               - "{{review_requested[4]}}"
               - "{{review_requested[5]}}"
```
etc

That should work fine. There's a hard limit IIRC on the number of users you can assign to, you can probably find this on the GitHub doc :)
