### DISCUSSION TITLE
Can mergify support pre/post hooks in their actions?

### DISCUSSION THREAD

**Discussion by v1v** [Mergifyio/mergify#2975] [Ideas]
## What

Do you think adding a pre/post hooks in the mergify actions could be something interesting to be enabled?

## Why

Some of the users of `mergify` asked the below:

> Would it be possible to tell mergify to run a custom script when backporting in order to fix the import paths?

### Use case:

Given two branches with one of them changing some of the go import paths. I'd like to enable the backport with a pre-hook run to transform go paths from one way to another one.

Therefore, I'd like to configure `mergify.yml` with something like:

```yaml
pull_request_rules:
  - name: backport patches to stable branch
    conditions:
      - base=main
      - label=backport-to-stable
    actions:
      backport:
        branches:
          - stable
        pre-hook: `scripts/transform.sh`
```

Where `scripts/transform.sh` transforms some paths in the code from the backport.

### Rationale

This could be helpful to extend mergify with some more custom, though it might also require some contracts to avoid any security expose or timeout the script if it takes longer than xx seconds.
