### DISCUSSION TITLE
"Open a PR" action?

### DISCUSSION THREAD

**Discussion by defung** [Mergifyio/mergify#3018] [Q&A] [answered]
Is there a way for Mergify to open a PR? Our team has a unique workflow. Would love to use mergify to automate some of these tasks.

We primarily have 2 branches: `main`, and `release/<version>` (e.g. `release/1.23`)

Our `main` branch is more like a `dev` branch, where most of our new changes go into. Once in a while, we have a bug fix, where we will fix directly in `release/<version>`. Once the bug fix is merged into `release/<version>`, we then do a merge from `release/<version>` branch back to `main`. This way, the bug fix will also be in `main`, AND we retain the original git commit hash.

Its sort of like `backport`, but from what I read, `backport` does a cherry pick, which isn't something we want. We want to retain the commit hash of the original merge to the `release/<version>` branch, but a cherry pick would generate a new commit hash.

So therefore, I want to create a rule with Mergify that does the above automatically. However, I'm not sure if its possible after reading the documentation.

I would need the following features in order to do this:
1. an `action` that can open a Pull Request
2. a way to get the current branch name

If there's such a way, it might look something like this:
```
pull_request_rules:
  - name: Bug fix merge
    conditions:
      - "#approved-reviews-by>=2"
      - check-success=Travis CI - Pull Request
      - base=release/*
      - label=ready-to-merge
    actions:
      merge:
        method: squash
      create_pr:      # <--- We need an action that would create a new PR
        - base=main
        - branch=<this_pr's_base_branch>  # <--- We also need a way to get the current PR's base branch name, so we can use it here
  - name: Automated release to Main merge
    conditions:
      - author=<mergify_user>
      - check-success=Travis CI - Pull Request
      - base=main
      - branch_name=release/*  # <--- would also need an attribute to match against the branch name of the PR
    actions:
      merge:
        method: merge
  - name: delete head branch after merge
    conditions:
      - merged
      - branch_name=release/*  # <--- same here
    actions:
      delete_head_branch:
```

Can you let me know if something like this is possible with mergify?
