### DISCUSSION TITLE
Configuration error details

### DISCUSSION THREAD

**Discussion by asbjornu** [Mergifyio/mergify#3046] [Q&A] [answered]
I've managed to commit a `mergify.yml` file that is seemingly invalid. Even though #69 is resolved, I'm not getting a lot of details on what the problem with my configuration file is:

<img width="842" alt="The Mergify configuration is invalid" src="https://user-images.githubusercontent.com/12283/130238243-389da643-5a8d-46e3-9cbf-a146a9514e70.png">

Clicking the "View more details on Mergify" link just takes me back to [the same URL](https://github.com/SwedbankPay/jekyll-plantuml-docker/pull/230/checks?check_run_id=3382166305). Hopefully you can let me know what the problem with the configuration file is, but I would also appreciate if the validation of the configuration file could be a bit more verbose in its output so I would be able to debug problems like these without any human assistance.

Here's my invalid config file:

```yaml
pull_request_rules:
  - name: Automatically approve dependency updates
    conditions:
      - and:
          label=dependencies
      - or:
          author~=^dependabot(|-preview)\[bot\]$
          author~=^github-actions\[bot\]$
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval
    conditions:
      - and:
          label=dependencies
      - or:
          author~=^dependabot(|-preview)\[bot\]$
          author~=^github-actions\[bot\]$
    actions:
      merge:
        method: merge
        strict: smart

  - name: Thank contributor
    conditions:
      - merged
      - -author~=^.*\[bot\]$
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
```

**Comment by sileht** [comment, marked as answer]
You missing the dash before each condition, eg:
```yaml
pull_request_rules:
  - name: Automatically approve dependency updates
    conditions:
      - and:
          - label=dependencies
      - or:
          - author~=^dependabot(|-preview)\[bot\]$
          - author~=^github-actions\[bot\]$
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval
    conditions:
      - and:
          - label=dependencies
      - or:
          - author~=^dependabot(|-preview)\[bot\]$
          - author~=^github-actions\[bot\]$
    actions:
      merge:
        method: merge
        strict: smart

  - name: Thank contributor
    conditions:
      - merged
      - -author~=^.*\[bot\]$
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
```

**Reply by asbjornu** [reply]
Thanks. But I have pretty much copy-pasted this from [the documentation](https://docs.mergify.io/conditions/#combining-conditions-with-operators), which does not use dashes:

```yaml
conditions:
  - or:
    - and:
        author=foo
        label=core
    - and:
        author=bar
        label=backend
```

**Reply by sileht** [reply]
Oh, the second example is wrong, I will fix it: https://github.com/Mergifyio/mergify-engine/pull/3047

**Reply by asbjornu** [reply]
Thanks. Now it complains that `length of value must be at least 2 for dictionary value @ pull_request_rules → item 0 → conditions → item 0 → and`. What I want is to express the following:

```js
if (label == "dependencies" && (author == "dependabot[bot]" || author == "github-actions[bot]")) { … }
```

Is it possible to express this without duplicating the `label` condition?

**Reply by sileht** [reply]
Then just:

```yaml
pull_request_rules:
  - name: Automatically approve dependency updates
    conditions:
      - label=dependencies
      - or:
          - author~=^dependabot(|-preview)\[bot\]$
          - author~=^github-actions\[bot\]$
    actions:
      review:
        type: APPROVE
```

`conditions` list already act as an `and`.
