### DISCUSSION TITLE
Dynamic backport with branches matching the given label

### DISCUSSION THREAD

**Discussion by v1v** [Mergifyio/mergify#3230] [Ideas]
Hi there,

Is it feasible to create backports dynamically based on the labels? Let me explain:

```cucumber
Given the GitHub labels: `1.0`, `1.1` and `1.2`
And the GitHub branches: `main`, `1.0`, `1.1`, `1.2`
When A GitHub Pull Request has been tagged to `1.1` and `1.2` and merged
Then a backport for `1.1` and `1.2` should be created.
```

The `.mergify.yml` might look like

```yaml
  - name: backport to 1.//d branches
    conditions:
      - base=main
      - label~=1.*
    actions:
      backport:
        branches:
          - {{ label }}
```

This approach could help to avoid editing the `.mergify.yml` when a new branch is created. Though, it might imply it's not reproducible since GitHub labels can be modified, maybe?

Potentially, it could be added a label manipulation in case the branch does not fully match the name of the label. For instance, some people use a branch strategy based on numbers (Major.Minor) and labels with `vMajor.Minor`. Therefore, `v` is not needed.

So something like:

```yaml
  - name: backport to v1.x branches
    conditions:
      - base=main
      - label~=v1.*
    actions:
      backport:
        branches:
          - {{ label | regex_replace('^v(.*)$', '\\1') }}
```
