### DISCUSSION TITLE
GitHub branch protections with queues

### DISCUSSION THREAD

**Discussion by ghost** [Mergifyio/mergify#3432] [Ideas]
👋🏻

New comer to using mergify and potentially unique requirements, however... I'd like to propose the discussion about moving/configuring the GitHub branch protection checks that mergify upholds.

Currently, the rules are added to the `pull_request_rules.conditions` causing PRs not to be added to the queue unless they fulfil these extra rules. However, since our CI can take considerable time, it is useful for us to add PRs into the queue (and therefore rebase them to keep them up-to-date) purely based on the mergify conditions and enforce the branch protections rules at merge time (`queue_rules.conditions`).  

We investigation removing the GitHub branch protection rules and enforcing everything in mergify but GitHub does not offer a way to prevent our users from manually pressing the merge button in a PR.

```
queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"

pull_request_rules:
  - name: lgtm-default
    conditions:
      - "base=master"
      - "label=LGTM"
    actions:
      queue:
        name: default
        update_method: rebase
```

![image](https://user-images.githubusercontent.com/77615995/137925170-e8aab4a2-6928-4013-a5cd-03c3b81db57d.png)

![image](https://user-images.githubusercontent.com/77615995/137925729-f7e4694d-9ec9-48ab-a6c0-53de4a0aec00.png)
