### DISCUSSION TITLE
# of PRs targeting attribute

### DISCUSSION THREAD

**Discussion by cameronjump** [Mergifyio/mergify#3475] [Ideas]
```
pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
```
This rule fails when there are still PRs targeting that branch. It would be nice to be able to add an attribute that only tries to delete once there are no PRs targeting that branch, so that deleting the branches would happen more consistently.
