### DISCUSSION TITLE
Override a Schedule Condition

### DISCUSSION THREAD

**Discussion by kejek** [Mergifyio/mergify#3604] [Q&A]
Is it possible to override a schedule condition?

For example, we are thinking of using a MON-TUES and THURS-FRI schedule, with no merges allowed on Wednesday (server updates).

But, sometimes we need to get something in, and its super important, so we need to override the merge restriction. Is this doable?

Thanks!

**Comment by sileht** [comment]
You can use something like:
```yaml
conditions:
  - or:
    - schedule: MON-TUE
    - schedule: THU-FRI
    - label: bypass-schedule
```
