### DISCUSSION TITLE
Matching Pull Requests with Task Lists does not work

### DISCUSSION THREAD

**Discussion by mxkh** [Mergifyio/mergify#3606] [Q&A] [answered]
Hello! I am configuring Mergify and added rules for the checklist but they don't work for me.

I am using the following pull request template
```markdown
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Hot fix (non-breaking change which fixes an issue on production)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a fixtures update
- [ ] This change requires a migrations update

## How Has This Must be Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the PSR and Symfony style guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have added or updated fixtures
- [ ] I did not forget to add or update entity mapping for the Laravel
- [ ] I have check that migrations work well on empty database
- [ ] I have added or update ENV variables

```
and following Mergify config
```yml
queue_rules:
  - name: default
    conditions:
      - check-success=Static checks (PHP7.3, Symfony ^4.4)
      - check-success=Test application

pull_request_rules:
  - name: automatic merge for master using queue
    conditions:
      - check-success=Static checks (PHP7.3, Symfony ^4.4)
      - check-success=Test application
      - "#approved-reviews-by>=1"
      - base=master
      - label=qa-approved
      - label=po-approved
      - body~=(?m)^\[(X|x)\] My code follows the PSR and Symfony style guidelines
      - body~=(?m)^\[(X|x)\] I have performed a self-review of my own code
      - body~=(?m)^\[(X|x)\] I have commented my code, particularly in hard-to-understand areas
      - body~=(?m)^\[(X|x)\] I have made corresponding changes to the documentation
      - body~=(?m)^\[(X|x)\] My changes generate no new warnings
      - body~=(?m)^\[(X|x)\] I have added tests that prove my fix is effective or that my feature works
      - body~=(?m)^\[(X|x)\] New and existing unit tests pass locally with my changes
      - body~=(?m)^\[(X|x)\] Any dependent changes have been merged and published in downstream modules
      - body~=(?m)^\[(X|x)\] I have checked my code and corrected any misspellings
      - body~=(?m)^\[(X|x)\] I have added or updated fixtures
      - body~=(?m)^\[(X|x)\] I did not forget to add or update entity mapping for the Laravel
      - body~=(?m)^\[(X|x)\] I have check that migrations work well on empty database
      - body~=(?m)^\[(X|x)\] I have added or update ENV variables
    actions:
      queue:
        name: default
        method: squash
        update_method: rebase
  - name: automatic merge for develop using queue
    conditions:
      - check-success=Static checks (PHP7.3, Symfony ^4.4)
      - check-success=Test application
      - "#approved-reviews-by>=1"
      - base=develop
      - label=qa-approved
      - label=po-approved
      - body~=(?m)^\[(X|x)\] My code follows the PSR and Symfony style guidelines
      - body~=(?m)^\[(X|x)\] I have performed a self-review of my own code
      - body~=(?m)^\[(X|x)\] I have commented my code, particularly in hard-to-understand areas
      - body~=(?m)^\[(X|x)\] I have made corresponding changes to the documentation
      - body~=(?m)^\[(X|x)\] My changes generate no new warnings
      - body~=(?m)^\[(X|x)\] I have added tests that prove my fix is effective or that my feature works
      - body~=(?m)^\[(X|x)\] New and existing unit tests pass locally with my changes
      - body~=(?m)^\[(X|x)\] Any dependent changes have been merged and published in downstream modules
      - body~=(?m)^\[(X|x)\] I have checked my code and corrected any misspellings
      - body~=(?m)^\[(X|x)\] I have added or updated fixtures
      - body~=(?m)^\[(X|x)\] I did not forget to add or update entity mapping for the Laravel
      - body~=(?m)^\[(X|x)\] I have check that migrations work well on empty database
      - body~=(?m)^\[(X|x)\] I have added or update ENV variables
    actions:
      queue:
        name: default
        method: squash
        update_method: rebase
  - name: assign author to the PR
    conditions:
      - -closed
    actions:
      assign:
        add_users:
          - "{{author}}"
  - name: assign reviewers
    conditions:
      - -closed
    actions:
      request_reviews:
        users:
          - mxkh
          - m0sviatoslav
          - niksynov
          - bilyuk
  - name: add a link on a merge queue
    conditions:
      - -closed
    actions:
      comment:
        message: "😎 To verify a merge queue follow this link https://dashboard.mergify.com/github/companyname/queues"
  - name: add a link on a how merge queue works
    conditions:
      - -closed
    actions:
      comment:
        message: "🤓 To read how merge queue works follow this link https://docs.mergify.com/actions/queue/"
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: convert to draft on checks failure
    conditions:
      - "#check-failure>0"
    actions:
      edit:
        draft: True
  - name: add hotfix label
    conditions:
      - head~=^hotfix/
    actions:
      label:
        add:
          - hotfix
  - name: add bugfix label
    conditions:
      - head~=^bugfix/
    actions:
      label:
        add:
          - bugfix
  - name: add feature label
    conditions:
      - head~=^feature/
    actions:
      label:
        add:
          - feature

```
I also validated regex
![CleanShot 2021-11-16 at 22 33 16@2x](https://user-images.githubusercontent.com/3147546/142069369-76a62fce-3639-4801-80ff-1982c42212fe.png)
and Meegify config
<img width="1536" alt="CleanShot 2021-11-16 at 22 35 13@2x" src="https://user-images.githubusercontent.com/3147546/142069549-fd910882-2e8e-4763-9d5e-7605cfb6e48f.png">

Everything looks fine, but when I mark some checkboxes. from the checklist, Mergify does not parse them. What can be wrong?
Summary report looks like this
<img width="863" alt="CleanShot 2021-11-16 at 22 42 18@2x" src="https://user-images.githubusercontent.com/3147546/142070511-c1e53e95-9d66-48c8-af09-d18128f3a7b6.png"> 
Thank you in advance!
