### DISCUSSION TITLE
Don't update the pull request branch

### DISCUSSION THREAD

**Discussion by asbjornu** [Mergifyio/mergify#3758] [Q&A]
Is it possible for Mergify to **not** merge the target branch into the pull request to keep it up to date? Since I only use Mergify with Dependabot pull requests, I would like Dependabot to keep its pull requests up to date itself. Mergify's merge commits into Dependabot's pull requests disables Dependabot's functionality to keep its pull requests up to date, so I would like to disable it somehow.

Another option would be for Mergify to add `@dependabot rebase` comments to the PR to nudge Dependabot to rebase the PR.

**Comment by jd** [comment]
1. You can exclude PR from dependabot in your queue rule, just use `author!=dependabot[bot]` in your conditions.
2. You can use something like this to update dependabot:

```yaml
  - name: dependabot update
    conditions:
      - author=dependabot[bot]
      - "#commits-behind>0"
    actions:
      comment:
        bot_account: some-account-with-write-access
        message: "@dependabot rebase"
```

You need to use a bot account because Dependabot will refuse to rebase a PR if the author is an app AFAIK.

**Reply by asbjornu** [reply]
Won't excluding Dependabot PR's from the queue also exclude them from being automatically merged? What I want Mergify to do is to merge Dependabot's PR's into the target branch (usually `main`), **not** merge `main` into Dependabot's PR branches.

**Reply by jd** [reply]
You could merge without using the queue.

```yaml
 - name: dependabot automatic merge
    conditions:
      - author=dependabot[bot]
      # Uncomment this if you want to be sure they are only merged when up-to-date
      # - "#commits-behind=0"
    actions:
      merge:
```

**Reply by asbjornu** [reply]
So eliminating the queue will stop Mergify from updating PRs? Can I add conditions to the `merge` action so my current queue conditions are applied, or will the required GitHub Checks be used as previously?

**Reply by jd** [reply]
> So eliminating the queue will stop Mergify from updating PRs?

Yes.

> Can I add conditions to the merge action so my current queue conditions are applied, or will the required GitHub Checks be used as previously?

You can just copy the same conditions that you use for the `queue` action for sure.

Feel free to share your configuration.

**Reply by asbjornu** [reply]
Thanks! I got it to work with the following configuration:

```yaml
pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - '#commits-behind=0' # Only merge up to date pull requests
      - check-success=build
      - check-success=license/cla
      - check-success=verify
      - check-success=spec
    actions:
      merge:

  - name: Thank contributor
    conditions:
      - merged
      - -author~=^.*\[bot\]$
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
```
