### DISCUSSION TITLE
How to remove a stuck PR from merge queue

### DISCUSSION THREAD

**Discussion by humblec** [Mergifyio/mergify#3904] [General]
We have a condition where one of the PR is stuck in merge queue and blocking all the other PRs in the queue . Is there a command or some method to remove a PR from merge queue ?

**Comment by jd** [comment]
Hi @humblec 

You just have to make the PR unmatch the conditions to be put in the queue. You could use a label for this, for example:

```yaml
- name: queue when ready
  conditions:
    - "#approved-reviews-by>=1"
    - check-success=myci
    - label!=do-not-queue
  actions:
    queue:
      name: default
```

If you add the label `do-not-queue` to the PR, the conditions do not match anymore and the PR will be removed from the queue.
