### DISCUSSION TITLE
Match files in root directory of repository

### DISCUSSION THREAD

**Discussion by njlaw** [Mergifyio/mergify#5033] [Q&A]
Hello,

I have been trying to match files that are in the root directory of the repository without success.  Currently, I have:

```yml
pull_request_rules:
  - name: Automatic Merge on Selected Projects
    conditions:
      - -files~=^[^/]+ # This should require that there be no files affected by the commits in the root of the repository
      - ...
```

However, even when no files at the root of the repository are affected in the commits of a pull request, this condition does not match.
![image](https://user-images.githubusercontent.com/850257/181347897-8f4f1a75-59ad-4bd7-b583-2ddff2faea63.png)

Based on https://docs.mergify.com/conditions/#how-to-match-lists, I am assuming that there is no leading `/` when parsing filename in the repository.

Any insight into how this attribute is evaluated would be appreciated!  I interpreted the example of `files~=^(README.md|CONTRIBUTING.md)$ is true if the file README.md or CONTRIBUTING.md is modified in the pull requests.` to mean that regex is supported.
