### DISCUSSION TITLE
Trouble trying to assign "author" as assignee for PR

### DISCUSSION THREAD

**Discussion by benoy-sifive** [Mergifyio/mergify#5039] [Q&A]
Can someone help me with the syntax?

Here is what I have so far:
```
  - name: auto assign author to PR when blank
    conditions:
      - 'assignee=""'
    actions:
      assign:
        add_users: 
          - "{{ author }}"
```

GitHub complains:
```
Invalid condition 'assignee=""'. Invalid GitHub login @ pull_request_rules → item 0 → conditions → item 0

Invalid GitHub login
```
