### DISCUSSION TITLE
How to exclude particular dependency (`@types/node`)

### DISCUSSION THREAD

**Discussion by unional** [Mergifyio/mergify#5049] [Q&A]
I want to avoid merging automatically for a particular dependency: `@types/node`.

The reason is being that package should match the minimum version of NodeJS the project supports, instead of always getting the latest.

I tried something like this but it doesn't work:

```
  - name: automatic merge for Renovate pull requests (except major)
    conditions:
      - author=renovate[bot]
      - head~=^(?!(major-))
      - title~=(?!(@types\/node))
```

Am I missing something?

**Comment by jd** [comment]
Would you have an example PR that you would like to exclude to show? that'd help.
I'm not really knowledgeable on renovate PR format.

**Reply by unional** [reply]
Here is an example:
https://github.com/unional/unpartial/pull/111

Thx~

**Reply by jd** [reply]
If you just want to ignore node, you can do this:

```yaml
  - name: automatic merge for Renovate pull requests (except major)
    conditions:
      - author=renovate[bot]
      - -title~=update dependency @types\/node
```
That should work (You can check in the config editor in your Mergify dashboard).

Now if you want to only ignore major version, Renovate does not really help. I'd try something like this:

```yaml
  - name: automatic merge for Renovate pull requests (except major)
    conditions:
      - author=renovate[bot]
      - not:
         # Do not merge if the update is about node but the branch name is not node-14
         - and:
            - title~=update dependency @types\/node
            - -head~=^renovate/node-14
```

This has the disadvantage to having you specifying the "14" in the Mergify rules, but I'm not sure there's any other good way since Renovatebot does not add any useful label nor easily parsable metadata in the PR.

**Reply by unional** [reply]
Thanks. I want to exclude major bump for any packages and ignore `@types/node` completely.

Do you think the following will work?

```yml
  - name: automatic merge for Renovate pull requests (except major and @types/node)
    conditions:
      - author=renovate[bot]
      - and:
        - head~=^(?!major-)
        - -title~=update dependency @types\/node
    actions:
      merge:
        method: squash
```
