### DISCUSSION TITLE
This pull request cannot be embarked for merge

### DISCUSSION THREAD

**Discussion by andrewhsu** [Mergifyio/mergify#5065] [Q&A] [answered]
I've configured the free plan of mergify on a test repo to try out some merge queue scenarios. Specifically, I'm trying to see how mergify performs `rebase` to keep a PR up-to-date with its base branch instead of `merge`.

I have the following `.mergify.yml` file:
```yaml
queue_rules:
  - name: default
    allow_inplace_checks: true
    conditions:
      - check-success=render
      - check-success=Lint go files
      - check-success=Lint python files
      - check-success=Lint shell scripts
      - check-success=Run tests (linux, amd64)
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=render
      - check-success=Lint go files
      - check-success=Lint python files
      - check-success=Lint shell scripts
    actions:
      label:
        add:
          - queued
      queue:
        name: default
        method: rebase
        update_method: rebase
```

However, when I send the command via github comment:
```
@Mergifyio queue
```

It fails to add the PR to the queue with the following check failure, even though i can login to the mergify dashboard with `andrewhsu`:

<img width="1221" alt="Screenshot 2023-01-05 at 2 39 31 AM" src="https://user-images.githubusercontent.com/57640/210737665-7dc5db65-cb76-42dd-bcf9-8973a40e72f1.png">

Am I missing some other configuration step to allow mergify to perform this action?
