### DISCUSSION TITLE
all check fail still match

### DISCUSSION THREAD

**Discussion by DrAugus** [Mergifyio/mergify#5067] [Q&A] [answered]
why did all the checks fail, still match?

![1](https://user-images.githubusercontent.com/34206897/216285631-18a88b76-ee0d-496f-bac1-42e7300c449e.png)
https://github.com/DrAugus/draugus.github.io/pull/208

![2](https://user-images.githubusercontent.com/34206897/216285739-f41d3e30-50e2-461e-aac6-853c1c2779f1.png)
https://github.com/DrAugus/draugus.github.io/runs/11025552389

**Comment by DrAugus** [comment]
other case

```yml
  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=build
    actions:
      merge:
        method: merge
```

![1](https://user-images.githubusercontent.com/34206897/216306751-70a53829-d113-4c90-ba0f-66aa146466a4.png)
https://github.com/DrAugus/github-piy8bt/pull/6/checks?check_run_id=11058856645
![2](https://user-images.githubusercontent.com/34206897/216306954-2314b47b-91ee-4c30-83ba-553a12c32a03.png)

**Comment by DouglasBlackwood** [comment]
Hi

Have you checked that you didn't misspell the CI names?

Anyway, I would recommend using this:

```yaml
- and:
  - check-success:ci
```

Instead of:

```yaml
- not:
  - or:
    - check-failure:ci
```

The condition will be checked in the second case when the CI is pending.
