### DISCUSSION TITLE
How would you do to forbid the author as reviewer?

### DISCUSSION THREAD

**Discussion by barnou-psee** [Mergifyio/mergify#5068] [Q&A]
Hi, I'm using mergify to setup a list of rules to automatically add review request. I would like to add review request but not the author. 
Like 

```
pull_request_rules:
  - name: Assign reviewers on Python files
    conditions:
      - files~=\.py$
    actions:
      request_reviews:
        - foo
        - bar
        - baz
        - qux   
```

But the PR author is `bar`, how to do you tell mergify that `bar` cannot review this PR? Is it automatically handled by mergify?

**Comment by DouglasBlackwood** [comment]
Hi. 
I don't know if there is a way to do this. What we do at Mergify is request a review from a team, like this:

```yaml
  - name: request review
    conditions:
      - -author=mergify-ci-bot
      - -merged
      - -closed
      - ...
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "review-requested!=@devs"
    actions:
      request_reviews:
        teams:
          - devs
```

This allows requesting reviews from the dev team on opened pull requests not yet approved.

There may be another way with [template strings](https://docs.mergify.com/configuration/#template). Each condition is a template string where you can use pull request properties, like `{{author}}`, or statements like loops or conditions. But I'm not sure you can carry out what you want.

Hope this helps
