### DISCUSSION TITLE
How to perform an action (remove a label) after a PR has successfully merged?

### DISCUSSION THREAD

**Discussion by mjhoy** [Mergifyio/mergify#5073] [Q&A]
Apologies if this is clearly explained in the documentation somewhere, but I'm having trouble figuring out how to perform an action — removing a label — after a PR has successfully been merged from the merge queue.

We use a label, `Ready to merge`, to put PRs in the queue:

```yaml
pull_request_rules:
  - name: Queue via label
    conditions:
      - "base=master"
      - "label=Ready to Merge"
    actions:
      queue:
        name: default
```

Is there a way to trigger the remove label action once the PR has been merged?

Thanks.
Mikey

**Comment by jd** [comment]
Hi @mjhoy,

Sure, you can write this:

```
- name: remove Ready to Merge 
  conditions:
    - merged
    - base=master
  actions:
    label:
      remove:
         - Ready to Merge
```

Let me know if that works for you!
