### DISCUSSION TITLE
`Require branches to be up to date` is not compatible with `update_method=rebase` if `update_bot_account` isn't set.

### DISCUSSION THREAD

**Discussion by grondo** [Mergifyio/mergify#5087] [Q&A]
Hi, We just started getting this error on PRs on our repo in the past 24 hours. We have not changed branch protection rules or the mergify config recently, so we're wondering how to work around this issue?  This was working within the last couple days and is affecting multiple users (not just a single account).

Our `mergify.yml`
```yaml
queue_rules:
  - name: default
    conditions:
      - base=master
      - status-success="validate commits"
      - status-success="spelling"
      - status-success="flux-sched check"
      - status-success="flux-accounting check"
      - status-success="python linting"
      - status-success="bionic"
      - status-success="bionic - 32 bit"
      - status-success="bionic - gcc-8,content-s3,distcheck"
      - status-success="bionic - py3.7,clang-6.0"
      - status-success="bionic - test-install"
      - status-success="focal - py3.8"
      - status-success="el7"
      - status-success="el8"
      - status-success="fedora33 - gcc-10,py3.9"
      - status-success="fedora34 - gcc-11.2,py3.9"
      - status-success="coverage"
      - status-success="address-sanitizer check"
      - label="merge-when-passing"
      - label!="work-in-progress"
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
      - -title~=^\[*[Ww][Ii][Pp]

pull_request_rules:
  - name: rebase and merge when passing all checks
    conditions:
      - base=master
      - label="merge-when-passing"
      - label!="work-in-progress"
      - -title~=^\[*[Ww][Ii][Pp]
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
    actions:
      queue:
        name: default
        method: merge
        update_method: rebase
  - name: remove outdated approved reviews
    conditions:
      - author!=@core
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: false
        message: |
          Approving reviews have been dismissed because this pull request
          was updated.
```

Example of failing PR: https://github.com/flux-framework/flux-core/pull/5144

Apologies if this is something obvious!
