### DISCUSSION TITLE
priority_rules doesn't work and PR got stuck

### DISCUSSION THREAD

**Discussion by WayneYe** [Mergifyio/mergify#5089] [Q&A] [answered]
Hi folks,
I have the following content in my project's `.mergify.yml`:

```
queue_rules:
  - name: default
    conditions: &build-conditions
      - base=master
      - label=merge-ready
 
    priority_rules:
      - name: regression-fix  # Treat regression-fixes as high priority.
        conditions:
          - label=regression-fix
        priority: high
pull_request_rules:
  - name: auto-merge-pr-to-master
    conditions:
      - and: *build-conditions
      - "-label=regression-fix"
    actions:
      queue: &queue-def
        method: squash
        name: default
        commit_message_template: |-
          {{ title }} (#{{ number }})

          {{ body }}
```

Right now any PR with this `regression-fix` PR was not merged, others without this label merged as normal, any thing wrong here, please?
