### DISCUSSION TITLE
How to trim empty lines from commit message?

### DISCUSSION THREAD

**Discussion by thomaseizinger** [Mergifyio/mergify#5091] [General]
We have the following commit message template:

```jinja2
{{ title }}

{{ body | get_section("## Description", "") }}

Pull-Request: #{{ number }}.
{# Here comes some fancy Jinja2 stuff for correctly attributing co-authorship: #}
{% for commit in (commits | unique(False, 'email_author')) | rejectattr("author", "==", author) %}
  {% if commit.parents|length == 1 %}
Co-Authored-By: {{ commit.author }} <{{ commit.email_author }}>
  {% endif %}
{% endfor %}
{# GitHub requires that the `Co-authored-by` lines are AT THE VERY END of a commit, hence nothing must come after this. #}
```

Here is an example commit that got generated: https://github.com/libp2p/rust-libp2p/commit/b8ceeccdc6a4d38ebe77d74cab3c66be072f16db

As you can see, there are multiple empty lines. Ideally, I would like to control these empty lines somehow. My expectation was that - because I did not add any empty lines between `Pull-Request` and the comment - there would be no empty lines. Yet it seems that the template engine adds additional empty lines?

Can this be avoided somehow?

Also, not all our PRs have a `## Description` section (or it is empty). Ideally I'd like to somehow avoid additional empty lines in that case.

If we go after https://cbea.ms/git-commit/, then a commit message should never have more than a single empty line as a separator. That is what I want to achieve. Would it be possible to automatically trim additional empty lines from inside the template?

**Comment by Kontrolix** [comment]
Hi,
There is [whitespace control](https://jinja.palletsprojects.com/en/3.0.x/templates/#whitespace-control) in Jinja. You should probably add a minus to your template like this to avoid rendering it.
```jinja
{{ title }}

{{ body | get_section("## Description", "") }}

Pull-Request: #{{ number }}.
{# Here comes some fancy Jinja2 stuff for correctly attributing co-authorship: #}
{%- for commit in (commits | unique(False, 'email_author')) | rejectattr("author", "==", author) -%}
  {%- if commit.parents|length == 1 -%}
Co-Authored-By: {{ commit.author }} <{{ commit.email_author }}>
  {%- endif -%}
{%- endfor -%}
{# GitHub requires that the `Co-authored-by` lines are AT THE VERY END of a commit, hence nothing must come after this. #}
```
Hope it's what you are looking for 😉

**Reply by thomaseizinger** [reply]
Thanks I will try this!

In the docs, it looks like newlines will be stripped as well then. Can that be avoided?

**Reply by Kontrolix** [reply]
When I tried this template I didn't notice such behavior. Let me know if you still have trouble with newlines.

**Reply by thomaseizinger** [reply]
I tried it on https://j2live.ttl255.com/ with the following test-data and it is missing the newlines inbetween. I am working on it in this PR: https://github.com/libp2p/rust-libp2p/pull/4104

```yml
commits:
  - email_author: foo@example.com
    author: foo
    parents:
      - abc
  - email_author: bar@example.com
    author: bar
    parents:
      - abc
  - email_author: bar@example.com
    author: bar
    parents:
      - abc
  - email_author: xyz@example.com
    author: xyz
    parents:
      - abc
      - def
  - email_author: foo@example.com
    author: foo
    parents:
      - abc
  - email_author: xyz@example.com
    author: xyz
    parents:
      - abc
  - email_author: xyz1@example.com
    author: xyz1
    parents:
      - abc
author: test
```
