### DISCUSSION TITLE
Queue command without arguments no longer works (results didn't understand the arguments of the command queue)

### DISCUSSION THREAD

**Discussion by Mic92** [Mergifyio/mergify#5112] [Q&A] [answered]
On all my repositories, I am no longer able to to use the `mergify queue` command: https://github.com/nix-community/nix-eval-jobs/pull/299

The error is always the same:

```
❌ Sorry but I didn't understand the arguments of the command queue. Please consult [the commands documentation](https://docs.mergify.com/commands/) 📚.
```

This is my `.mergify.yaml`:

```
queue_rules:
  - name: default
    merge_conditions:
      - check-success=collect

defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      method: rebase

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label~=merge-queue|dependencies
    actions:
      queue: {}

```
