### DISCUSSION TITLE
Feature Request: Expand "edit" action to include PR body editing

### DISCUSSION THREAD

**Discussion by leseb** [Mergifyio/mergify#5122] [Ideas]
Hello Mergify Team,

I hope you're doing well!

I wanted to suggest a new feature for the `edit` [action](https://docs.mergify.com/workflow/actions/edit/). It would be incredibly useful if we could use this action to edit the pull request body directly.

For example, something like this:

```yaml
- name: Add reviewers to PR description
  conditions:
    - "#approved-reviews-by>=1"
  actions:
    comment:
      message: |
        This pull request has been reviewed by: {{approved_reviews_by|join(', ')}}
    edit:
      body: |
        {{ pull_request.body }}

        ---
        Reviewed-by: {{approved_reviews_by|join(', ')}}
```

This would make it easier to automatically update PR descriptions with relevant information like who has approved the review **before** merging the PR. This information will be added to the merge commit if GitHub is set up this way.

Thanks for considering this enhancement, and keep up the great work!
