### DISCUSSION TITLE
How to Squash Using Github Squash and Merge?

### DISCUSSION THREAD

**Discussion by ryanolson-aumni** [Mergifyio/mergify#5123] [General]
What I'm hoping to accomplish is get a queue setup so that:
- PRs get queued
- Once they're ready to merge, they squash before merging
- I want it to include the pull request title and description (as you can configure in Github)
<img width="572" alt="Screenshot 2024-08-21 at 12 42 30 PM" src="https://github.com/user-attachments/assets/0459c098-6b94-4430-a710-8282ce99e781">

- Once I view the commits, I'd like for the commit to show as a Merge commit (this is desired, but I'm not sure if it's possible)

What's the best way to do this?

I tried:
```
queue_rules:
  - name: default
    merge_method: merge
    update_method: rebase
    update_bot_account: '{{ author }}'
    queue_conditions:
      - base=main
      - -conflict

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
      - label=automerge
    actions:
      queue:
        name: default

```

But then I see this on a test PR
<img width="1373" alt="Screenshot 2024-08-21 at 12 47 00 PM" src="https://github.com/user-attachments/assets/43a8b305-6b4c-48d0-8009-9369100336fe">

How can I solve this? Or is the best option doing a squash merge_method and configure it using templating?
