### DISCUSSION TITLE
Merge Queue and branch up to date protection

### DISCUSSION THREAD

**Discussion by tiagolobocastro** [Mergifyio/mergify#5138] [Q&A] [answered]
Hi folks,

I've enabled `batch_size` to allow multiple PRs merging at once but this came with an error:

```
The branch protection setting Require branches to be up to date before merging is not compatible with batch_size>1 and must be unset.
```

Then I set `queue_branch_merge_method: fast-forward` allowing the draft PR to merge and this does work now with the `Require branches to be up to date before merging` enabled.
This is the config I'm testing with:
```
queue_rules:
  - name: default
    update_method: rebase
    merge_method: merge
    allow_inplace_checks: true
    batch_size: 10
    queue_branch_merge_method: fast-forward

merge_queue:
  max_parallel_checks: 1
```

The downside is that it seems that even though `allow_inplace_checks: true` is enabled, now it always creates the draft PR? Is this expected?
Also is it possible to use mergify and the github merge queue together btw? Ex: rather than queue on a draft PR for example, send to the github merge queue?
