### ISSUE TITLE
Can’t use OR-condition on PR

### ISSUE THREAD

**Issue by ulysses4ever** [Mergifyio/mergify#5047]
## Expected Behavior

here’s an (I hope, standalone) excerpt of our proposed config:

```
pull_request_rules:
  - actions:
      label:
        add:
          - merge delay passed
    name: Wait for 2 days before validating merge
    conditions:
      - updated-at<2 days ago
      - or
        - label=merge me
        - label=squash+merge me
```

I expect it to apply a label under the said condition.

## Actual Behavior

Mergify complains:

> Invalid condition 'or - label=merge me - label=squash+merge me'. Invalid attribute @ pull_request_rules → item 0 → conditions → item 1

Worth noting: it worked when the condition had no ORs (instead of the OR it just had “label=merge me”). It’s just we want the OR.

## Specifications

  - Mergify Config URL: https://github.com/haskell/cabal/blob/7d06617e891d283f233dbddaeb7c3f06483d340c/.github/mergify.yml

**Comment by DouglasBlackwood** [comment]
Hi!

I think the `or` condition is missing a `:` character. Otherwise, it might be wrongly interpreted.
Can you test something like this?

```yaml
pull_request_rules:
  - actions:
      label:
        add:
          - merge delay passed
    name: Wait for 2 days before validating merge
    conditions:
      - updated-at<2 days ago
      - or
        - label=merge me
        - label=squash+merge me
```
