### ISSUE TITLE
new `bot_account` policy effectively makes rebase a premium feature when used in conjunction with renovate or other bots

### ISSUE THREAD

**Issue by DanySK** [Mergifyio/mergify#5074]
## Expected Behavior

It is possible to rebase PRs created by GitHub applications (such as dependabot or renovate) with the free version of mergify.
Worst case, with the previous behaviour (randomly picked user with sufficient rights)

## Actual Behavior

Leaving `bot_account` unspecified prevents the rebase (the user cannot be impersonated).
Specifying the bot account makes Mergify fail (premium feature)

## Steps to Reproduce the Problem

  1. Create a repository and enable renovate
  2. Configure mergify for rebasing out-of-date PRs from renovate[bot]
  3. Let renovate open a PR
  4. observe mergify fail

## Specifications

Example config triggering the problem

```yaml
pull_request_rules:
  - name: Auto-rebase if appropriately labeled or if the author is an authorized bot
    conditions:
      - or:
        - label=auto-update-rebase
        - and:
            - label=dependencies
            - or: &authors_are_bots
                - author=renovate[bot]
                - author=dependabot[bot]
      - -draft
      - -conflict
    actions:
      rebase:
```
